[project]
name = "notebook"
version = "0.1.0"
description = "Add a short description here"
authors = ["joconan <partrita@gmail.com>"]
channels = ["conda-forge"]
platforms = ["linux-64", "osx-arm64"]

[tasks]
start = "jupyter-lab --no-browser"

[dependencies]
python = ">=3.12.7,<3.13"
transformers = ">=4.45.2,<4.46"
jupyter = ">=1.1.1,<1.2"
pytorch = ">=2.4.1,<2.5"
